const GAME_DATA = {
  crtEffect: true,   // CRT screen effect overlay
  crtBlur:   0.5,    // CRT blur radius in pixels

  levels: [
    {
      initialBudget:            100,
      incomeInterval:           1800,
      dailyIncome:              50,
      incomeGrowthPercent:      10,
      cityPopulation:           100,
      deployRatio:              50,   // % of computer budget spent on weapon deployment each cycle
      deployProbability:        0.2,  // probability (0–1) that the computer deploys a weapon each cycle
      maxUnitsDeployedPerCycle: 1,    // max weapons the computer can deploy per budget cycle
      smartDeployment:          false,// if true, computer uses smart deployment policy
    },
    {
      initialBudget:            200,
      incomeInterval:           1800,
      dailyIncome:              75,
      incomeGrowthPercent:      10,
      cityPopulation:           250,
      deployRatio:              50,
      deployProbability:        0.3,
      maxUnitsDeployedPerCycle: 1,
      smartDeployment:          false,
    },
    {
      initialBudget:            300,
      incomeInterval:           1800,
      dailyIncome:              100,
      incomeGrowthPercent:      10,
      cityPopulation:           500,
      deployRatio:              50,
      deployProbability:        0.4,
      maxUnitsDeployedPerCycle: 1,
      smartDeployment:          false,
    },
    {
      initialBudget:            400,
      incomeInterval:           1800,
      dailyIncome:              150,
      incomeGrowthPercent:      20,
      cityPopulation:           1000,
      deployRatio:              50,
      deployProbability:        0.5,
      maxUnitsDeployedPerCycle: 2,
      smartDeployment:          false,
    },
    {
      initialBudget:            500,
      incomeInterval:           1800,
      dailyIncome:              200,
      incomeGrowthPercent:      20,
      cityPopulation:           2500,
      deployRatio:              50,
      deployProbability:        0.6,
      maxUnitsDeployedPerCycle: 2,
      smartDeployment:          false,
    },
    {
      initialBudget:            600,
      incomeInterval:           1800,
      dailyIncome:              250,
      incomeGrowthPercent:      20,
      cityPopulation:           5000,
      deployRatio:              60,
      deployProbability:        0.7,
      maxUnitsDeployedPerCycle: 2,
      smartDeployment:          false,
    },
    {
      initialBudget:            700,
      incomeInterval:           1800,
      dailyIncome:              300,
      incomeGrowthPercent:      30,
      cityPopulation:           10000,
      deployRatio:              70,
      deployProbability:        0.8,
      maxUnitsDeployedPerCycle: 2,
      smartDeployment:          false,
    },
    {
      initialBudget:            800,
      incomeInterval:           1800,
      dailyIncome:              350,
      incomeGrowthPercent:      30,
      cityPopulation:           25000,
      deployRatio:              80,
      deployProbability:        0.9,
      maxUnitsDeployedPerCycle: 3,
      smartDeployment:          false,
    },
    {
      initialBudget:            900,
      incomeInterval:           1800,
      dailyIncome:              400,
      incomeGrowthPercent:      30,
      cityPopulation:           50000,
      deployRatio:              90,
      deployProbability:        0.9,
      maxUnitsDeployedPerCycle: 3,
      smartDeployment:          false,
    },
    {
      initialBudget:            1000,
      incomeInterval:           1800,
      dailyIncome:              500,
      incomeGrowthPercent:      50,
      cityPopulation:           100000,
      deployRatio:              100,
      deployProbability:        1.0,
      maxUnitsDeployedPerCycle: 3,
      smartDeployment:          false,
    },
  ],
};
