const WEAPONS_DATA = {
  "weapons": {
    "patriot": {
      "shopPosition": 1,
      "image": "weapon_patriot.png",
      "name": "PATRIOT (DEFENSE)",
      "price": 20,
      "ammoPrice": 5,
      "defensive": true,
      "antiballistic": true,
      "bulletSize": 4,
      "bulletColor": "#00e5ff",
      "volume": 40,
      "projectileSpeed": 2.7
    },
    "shahed": {
      "shopPosition": 2,
      "image": "weapon_shahed.png",
      "name": "SHAHED",
      "price": 10,
      "ammoPrice": 2,
      "damage": 100,
      "explRadius": 22,
      "initialFireFrequency": 0,
      "shotsPerMinute": 30,
      "trajectoryAngleMin": 48,
      "trajectoryAngleMax": 58,
      "projectileSpeed": 1.0,
      "antiballistic": false,
      "bulletSize": 3,
      "bulletColor": "#ffeb3b",
      "volume": 20
    },
    "humvee": {
      "shopPosition": 3,
      "image": "weapon_m998.png",
      "name": "M998 GLH-L",
      "price": 50,
      "ammoPrice": 10,
      "damage": 200,
      "explRadius": 35,
      "initialFireFrequency": 0,
      "shotsPerMinute": 25,
      "trajectoryAngleMin": 48,
      "trajectoryAngleMax": 58,
      "projectileSpeed": 1.0,
      "antiballistic": false,
      "bulletSize": 4,
      "bulletColor": "#ff9800",
      "volume": 30
    },
    "howitzer": {
      "shopPosition": 4,
      "image": "weapon_howitzer.png",
      "name": "155mm Howitzer",
      "price": 150,
      "ammoPrice": 20,
      "damage": 300,
      "explRadius": 50,
      "initialFireFrequency": 0,
      "shotsPerMinute": 20,
      "trajectoryAngleMin": 48,
      "trajectoryAngleMax": 58,
      "projectileSpeed": 1.1,
      "antiballistic": false,
      "bulletSize": 5,
      "bulletColor": "#ff9800",
      "volume": 50
    },
    "sam": {
      "shopPosition": 5,
      "image": "weapon_sam.png",
      "name": "SAM-2",
      "price": 500,
      "ammoPrice": 40,
      "damage": 700,
      "explRadius": 80,
      "initialFireFrequency": 0,
      "shotsPerMinute": 15,
      "trajectoryAngleMin": 48,
      "trajectoryAngleMax": 58,
      "projectileSpeed": 1.2,
      "antiballistic": false,
      "bulletSize": 6,
      "bulletColor": "#ff5722",
      "volume": 65
    },
    "scud": {
      "shopPosition": 6,
      "image": "weapon_scud.png",
      "name": "SCUD",
      "price": 1000,
      "ammoPrice": 80,
      "damage": 2500,
      "explRadius": 140,
      "initialFireFrequency": 0,
      "shotsPerMinute": 10,
      "trajectoryAngleMin": 44,
      "trajectoryAngleMax": 54,
      "projectileSpeed": 1.4,
      "antiballistic": false,
      "bulletSize": 8,
      "bulletColor": "#ff1744",
      "volume": 80
    },
    "thaad": {
      "shopPosition": 7,
      "image": "weapon_thaad.png",
      "name": "THAAD (DEFENSE)",
      "price": 100,
      "ammoPrice": 10,
      "defensive": true,
      "antiballistic": true,
      "bulletSize": 4,
      "bulletColor": "#00e5ff",
      "volume": 40,
      "projectileSpeed": 3.5
    },
    "iskander": {
      "shopPosition": 8,
      "image": "weapon_iskander.png",
      "name": "Iskander",
      "price": 5000,
      "ammoPrice": 160,
      "damage": 10000,
      "explRadius": 260,
      "initialFireFrequency": 0,
      "shotsPerMinute": 5,
      "trajectoryAngleMin": 44,
      "trajectoryAngleMax": 54,
      "projectileSpeed": 1.5,
      "antiballistic": false,
      "bulletSize": 10,
      "bulletColor": "#d500f9",
      "volume": 100
    }
  }
};
